<?php
$this->breadcrumbs = array(
	Yii::t('site', 'Courses') => array('index'),
	$model->name,
);
?>
<script type="text/javascript">
$(document).ready(function() {
				$("a.accordion-body .chapter").click(function(e) {
					alert(this.id);
				});
				$(".playbutton").click(function(e){
					ajaxUrl = "<?php echo $this->createUrl("course/changeVideo") ?>";
					$.ajax({
						url : ajaxUrl,
						data : {
								videoId : this.id
								},
						dataType : "html",
						success : function(html){$("#lecture-content-wrapper").html(html);}
					});
				});
			});
</script>
<?php
	/*Yii::app()->clientScript->registerScript('activate-chapter', '
			$(document).ready(function() {
				$("a.accordion-body .chapter").click(function(e) {
					alert(this.id);
				});
				$(".playbutton").click(function(e){
					ajaxUrl = <?php echo $this->createUrl("course/changeVideo") ?>;
					$.ajax({
						type : post,
						url : ajaxUrl,
						data : {
								videoId : $this.id
								},
						dataType : "html",
						success : "function(html){$(#lecture-content-wrapper).html(html);}"
					});
				 	//$("video:nth-child(1)").attr("src",this.id+"/encodedVideo.mp4");
				 	//$("video:nth-child(1)").attr("src",this.id+"/encodedVideo.ogv");
				});
			});
	');*/
?>
<div class="container">
<h1><?php echo CHtml::encode($model->name); ?></h1>
<h3><?php echo Yii::t('site', 'By').' '.CHtml::encode($model->courseInstructorsShortString);?></h3>

<div id="course-tabs">
	<?php
	// create contents for the lecture tab 
	$chapIdx = 0;
	$lecturesTabContent = '
	<div class="row">
		<div class="accordion span3" id="chapter-accordion">';
	foreach ($chapters as $chapter)
	{
		$chapIdx++;
		$lecturesTabContent .= '
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#chapter-accordion" href="#chapter'.$chapIdx.'-collapse">
						'.$chapIdx.'. '.CHtml::encode($chapter->name).'
					</a>
				</div>
				<div id="chapter'.$chapIdx.'-collapse" class="accordion-body collapse chapter">
					<div class="accordion-inner">
						<ul>';
		// create a lecture list
		foreach ($chapter->lectures as $lecture)
		{
			$lecturesTabContent .= 
				'<li class="lecture">
					<div class="lecture-name">
						'.CHtml::encode($lecture->name).'
					</div>
					<div class="lecture-items">
						<!--<a href="'.$lecture->streamingUrl.'"><img src="'.Yii::app()->baseUrl.'/images/play.png" class="icon"></a> -->
						<a href="javascript:void(0)"><img id="'.$lecture->videoUrl.'" src="'.Yii::app()->baseUrl.'/images/play.png" class="icon playbutton"/></a>
						<!--<a href="'.$lecture->slideUrl.'"><img src="'.Yii::app()->baseUrl.'/images/slide.png" class="icon material"></a>-->
						<a href="contents/slide/slide.pdf"><img src="'.Yii::app()->baseUrl.'/images/slide.png" class="icon material"></a>
						<a href="'.$lecture->videoUrl."/encodedVideo.ogv".'"><img src="'.Yii::app()->baseUrl.'/images/video.png" class="icon material"></a>
					</div>	
				</li>';
		}
		$lecturesTabContent .= '</ul>
					</div><!-- end accordion-inner -->
				</div><!-- end chapter -->
			</div><!-- end accordion-group -->
		';
	}
	$lecturesTabContent .= '</div><!-- end accordion -->';
	$lecturesTabContent .= '<div id="lecture-content-wrapper" class="span9">';
	$lecturesTabContent .= $this->widget('application.extensions.videojs.EVideoJS', array(
						'options' => array(
							// Unique identifier, is autogenerated by default, useful for jQuery integrations.
							'id' => 'player',
							// Video and poster width in pixels
							'width' => 460,
							// Video and poster height in pixels
							'height' => 258,
							// Poster image absolute URL
							'poster' => false,
							// Absolute URL of the video in MP4 format
							'video_mp4' => $model->introUrl.".mp4",
							// Absolute URL of the video in OGV format
							//'video_ogv' => 'http://www.html5rocks.com/en/tutorials/video/basics/Chrome_ImF.ogv',
							'video_ogv' => $model->introUrl.".ogv",
							// Absolute URL of the video in WebM format
							//'video_webm' => 'http://www.html5rocks.com/en/tutorials/video/basics/Chrome_ImF.webm',
							// Use Flash fallback player ?
							'flash_fallback' => true,
							//'flash_fallback' => false,
							// Address of custom Flash player to use as fallback
							//'flash_player' => 'swf/ClassXPlayer_v2.swf',
							//'flash_player' => false,
							'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
							// Show controls ?
							'controls' => true,
							// Preload video content ?
							'preload' => true,
							// Autostart the playback ?
							'autoplay' => false,
							// Show VideoJS support link ?
							'support' => false,
							// Show video download links ?
							'download' => false,
						),
					), true);
	$lecturesTabContent .= '</div><!-- end lecture-content-wrapper -->
			</div><!-- end row -->';

	// create course tabs including lecture and problem set tabs.
	$this->widget('EBootstrapTabNavigation', array(
		'items' => array(
			array('label' => Yii::t('site', 'Lecture'), 'url' => '#lecture', 'active' => true),
			array('label' => Yii::t('site', 'Problem Set'), 'url' => '#problemset'),
			array('label' => Yii::t('site', 'Discussion'), 'url' => '#discussion'),
		),
)	);

	$this->beginWidget('EBootstrapTabContentWrapper');
		$this->beginWidget('EBootstrapTabContent', array(
			'active' => true,
			'id' => 'lecture',
		));
		echo $lecturesTabContent;
		$this->endWidget();
		$this->beginWidget('EBootstrapTabContent', array(
			'id' => 'problemset',
		));
		echo 'Problem set';
		$this->endWidget();
		$this->beginWidget('EBootstrapTabContent', array(
			'id' => 'discussion',
		));
		echo 'Discussion';
		$this->endWidget();
	$this->endWidget();
?>
</div><!-- end course-tabs -->
</div><!-- /container -->
