<form>
	<legend id="lecture-name"><?php echo $content->name; ?></legend>
	<div class="videoWrapper">
		<?php $this->widget('application.extensions.videojs.EVideoJS', array(
			'options' => array(
				// Unique identifier, is autogenerated by default, useful for jQuery integrations.
				'id' => false,
				// Video and poster width in pixels
				//'width' => 320,
				// Video and poster height in pixels
				//'height' => 240,
				// Poster image absolute URL
				'poster' => false,
				// Absolute URL of the video in MP4 format
				'video_mp4' => ResourcePath::getContentBaseUrl().$content->id.'/content/content.mp4',
				// Absolute URL of the video in OGV format
				'video_ogv' => ResourcePath::getContentBaseUrl().$content->id.'/content/content.ogv',
				//'video_ogv' => $model->intro_url.".ogv",
				// Absolute URL of the video in WebM format
				//'video_webm' => 'http://www.html5rocks.com/en/tutorials/video/basics/Chrome_ImF.webm',
				// Use Flash fallback player ?
				'flash_fallback' => true,
				//'flash_fallback' => false,
				// Address of custom Flash player to use as fallback
				//'flash_player' => 'swf/ClassXPlayer_v2.swf',
				//'flash_player' => false,
				'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
				// Show controls ?
				'controls' => true,
				// Preload video content ?
				'preload' => true,
				// Autostart the playback ?
				'autoplay' => false,
				// Show VideoJS support link ?
				'support' => false,
				// Show video download links ?
				'download' => false,
				),
			));
		?>
	</div><!-- end lecture-content-wrappero span9 -->
</form>
